Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202502.21.0"

  config.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"

  config.vm.provision "shell", path: "provision.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1         
    vb.memory = "1024"   
  end
end